id = "mermaid"
name = "Mermaid"
description = "Support for mermaid, the Python linter and formatter"
version = "0.1.0"
schema_version = 1
authors = []
repository = "https://github.com/zed-industries/zed"
